--STOCK SQL
--建表语句可以直接执行，但插入语句得根据具体id，修改后执行。（注意：执行时不能复制注释 既“--内容”内容）

--删表语句 （需按次循序依次删除）
--DROP TABLE STOCK_ADD_LOG;
--DROP TABLE STOCK_LOG;
--DROP TABLE STOCK;
--DROP TABLE STOCK_NAME;
--DROP TABLE STOCK_TYPE;
--DROP TABLE USERS;

--CREATE TABLE

	CREATE TABLE `USERS` (
	  `U_ID` INT(11) NOT NULL AUTO_INCREMENT,
	  `U_NAME` VARCHAR(255) NOT NULL,
	  `U_USERNAME` VARCHAR(255) NOT NULL,
	  `U_PASSWORD` VARCHAR(255) NOT NULL,
	  `U_ENABLED` INT(2) NOT NULL,
	  KEY `U_USERNAME` (`U_USERNAME`),
	  PRIMARY KEY (`U_ID`)
	) ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=UTF8;
	
	CREATE TABLE `AUTHORITY` (
	  `A_ID` INT(11) NOT NULL AUTO_INCREMENT,
	  `A_AUTHORITY` VARCHAR(20) NOT NULL,
	  `U_USERNAME` VARCHAR(255) NOT NULL,
	  PRIMARY KEY (`A_ID`),
	  KEY `U_USERNAME` (`U_USERNAME`),
	  CONSTRAINT `U_USERNAME` FOREIGN KEY (`U_USERNAME`) REFERENCES `USERS` (`U_USERNAME`)
	) ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=UTF8;
	
	CREATE TABLE `STOCK_TYPE` (
	  `S_T_ID` INT(11) NOT NULL AUTO_INCREMENT,
	  `S_T_TYPE` VARCHAR(30) NOT NULL,
	  `S_T_TEXT` VARCHAR(255) DEFAULT NULL,
	  PRIMARY KEY (`S_T_ID`)
	) ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=UTF8;
	
	CREATE TABLE `STOCK_NAME` (
	  `S_N_ID` INT(11) NOT NULL AUTO_INCREMENT,
	  `S_T_ID` INT(11) NOT NULL,
	  `S_N_NAME` VARCHAR(255) NOT NULL,
	  PRIMARY KEY (`S_N_ID`),
	  KEY `S_T_ID` (`S_T_ID`),
	  CONSTRAINT `S_T_ID` FOREIGN KEY (`S_T_ID`) REFERENCES `STOCK_TYPE` (`S_T_ID`)
	) ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=UTF8;
	
	CREATE TABLE `STOCK` (
	  `S_ID` INT(11) NOT NULL AUTO_INCREMENT,
	  `S_N_ID` INT(11) NOT NULL,
	  `U_ID` INT(11) NOT NULL,
	  `S_NUMBER_SUM` FLOAT(10,4) NOT NULL,
	  `S_NUMBER_CUR` FLOAT(10,4) NOT NULL,
	  `S_DATA_TYPE` INT(4) NOT NULL,
	  `S_TIME` VARCHAR(60) NOT NULL,
	  `S_VALID` INT(4) NOT NULL,
	  PRIMARY KEY (`S_ID`),
	  KEY `S_N_ID` (`S_N_ID`),
	  KEY `U_ID` (`U_ID`),
	  CONSTRAINT `U_ID` FOREIGN KEY (`U_ID`) REFERENCES `USERS` (`U_ID`),
	  CONSTRAINT `S_N_ID` FOREIGN KEY (`S_N_ID`) REFERENCES `STOCK_NAME` (`S_N_ID`)
	) ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=UTF8;
	
	CREATE TABLE `STOCK_ADD_LOG` (
	  `S_A_L_ID` INT(11) NOT NULL AUTO_INCREMENT,
	  `S_ID` INT(11) NOT NULL,
	  `S_A_L_NUMBER` FLOAT(10,4) NOT NULL,
	  `S_A_L_TIME` VARCHAR(30) NOT NULL,
	  PRIMARY KEY (`S_A_L_ID`),
	  KEY `S_ID` (`S_ID`),
	  CONSTRAINT `S_ID` FOREIGN KEY (`S_ID`) REFERENCES `STOCK` (`S_ID`)
	) ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=UTF8;
	
	CREATE TABLE `STOCK_LOG` (
	  `S_L_ID` INT(11) NOT NULL AUTO_INCREMENT,
	  `S_ID` INT(11) NOT NULL,
	  `S_L_NUMBER` FLOAT(10,4) NOT NULL,
	  `S_L_TIME` VARCHAR(30) NOT NULL,
	  PRIMARY KEY (`S_L_ID`),
	  KEY `S_L.S_ID` (`S_ID`),
	  CONSTRAINT `S_L.S_ID` FOREIGN KEY (`S_ID`) REFERENCES `STOCK` (`S_ID`)
	) ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=UTF8;


---------------------------------------------------------------------------------------------
--TEST DATA

	INSERT INTO `USERS` (U_NAME,U_USERNAME,U_PASSWORD,U_ENABLED) VALUES('系统用户','admin','admin','1');
	INSERT INTO `USERS` (U_NAME,U_USERNAME,U_PASSWORD,U_ENABLED) VALUES('测试用户','testuser','testuser','1');
	
	INSERT INTO AUTHORITY (U_USERNAME,A_AUTHORITY) VALUES ('ADMIN','ROLE_ADMIN');
	INSERT INTO AUTHORITY (U_USERNAME,A_AUTHORITY) VALUES ('ADMIN','ROLE_STOCK');
	INSERT INTO AUTHORITY (U_USERNAME,A_AUTHORITY) VALUES ('TESTUSER','ROLE_STOCK');
	
	INSERT INTO STOCK_TYPE (S_T_TYPE,S_T_TEXT) VALUES ('kg','千克');
	
	INSERT INTO STOCK_NAME (S_T_ID,S_N_NAME) VALUES((SELECT S_T_ID FROM STOCK_TYPE WHERE S_T_TYPE = 'kg'),'土豆');
	INSERT INTO STOCK_NAME (S_T_ID,S_N_NAME) VALUES((SELECT S_T_ID FROM STOCK_TYPE WHERE S_T_TYPE = 'kg'),'白菜');
	INSERT INTO STOCK_NAME (S_T_ID,S_N_NAME) VALUES((SELECT S_T_ID FROM STOCK_TYPE WHERE S_T_TYPE = 'kg'),'青椒');
	INSERT INTO STOCK_NAME (S_T_ID,S_N_NAME) VALUES((SELECT S_T_ID FROM STOCK_TYPE WHERE S_T_TYPE = 'kg'),'胡萝卜');
	INSERT INTO STOCK_NAME (S_T_ID,S_N_NAME) VALUES((SELECT S_T_ID FROM STOCK_TYPE WHERE S_T_TYPE = 'kg'),'大葱');
	INSERT INTO STOCK_NAME (S_T_ID,S_N_NAME) VALUES((SELECT S_T_ID FROM STOCK_TYPE WHERE S_T_TYPE = 'kg'),'姜');
	
	
	INSERT INTO STOCK (S_N_ID,U_ID,S_NUMBER_SUM,S_NUMBER_CUR,S_DATA_TYPE,S_TIME,S_VALID) VALUES 
	((SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆'),(SELECT U_ID FROM USERS WHERE U_USERNAME = 'admin'),'0','0','1','20140921240000','1');
		INSERT INTO STOCK (S_N_ID,U_ID,S_NUMBER_SUM,S_NUMBER_CUR,S_DATA_TYPE,S_TIME,S_VALID) VALUES 
	((SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜'),(SELECT U_ID FROM USERS WHERE U_USERNAME = 'admin'),'0','0','1','20140921240000','1');
	INSERT INTO STOCK (S_N_ID,U_ID,S_NUMBER_SUM,S_NUMBER_CUR,S_DATA_TYPE,S_TIME,S_VALID) VALUES 
	((SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '青椒'),(SELECT U_ID FROM USERS WHERE U_USERNAME = 'admin'),'0','0','1','20140921240000','1');
	INSERT INTO STOCK (S_N_ID,U_ID,S_NUMBER_SUM,S_NUMBER_CUR,S_DATA_TYPE,S_TIME,S_VALID) VALUES 
	((SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '胡萝卜'),(SELECT U_ID FROM USERS WHERE U_USERNAME = 'admin'),'0','0','1','20140921240000','1');
	INSERT INTO STOCK (S_N_ID,U_ID,S_NUMBER_SUM,S_NUMBER_CUR,S_DATA_TYPE,S_TIME,S_VALID) VALUES 
	((SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '大葱'),(SELECT U_ID FROM USERS WHERE U_USERNAME = 'admin'),'0','0','1','20140921240000','1');
	INSERT INTO STOCK (S_N_ID,U_ID,S_NUMBER_SUM,S_NUMBER_CUR,S_DATA_TYPE,S_TIME,S_VALID) VALUES 
	((SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '姜'),(SELECT U_ID FROM USERS WHERE U_USERNAME = 'admin'),'0','0','1','20140921240000','1');
	
	INSERT INTO STOCK_ADD_LOG (S_ID,S_A_L_NUMBER,S_A_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'110','20140913');
	UPDATE STOCK SET S_NUMBER_SUM=S_NUMBER_SUM+110,S_NUMBER_CUR=S_NUMBER_CUR+110 
	WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆');
	INSERT INTO STOCK_ADD_LOG (S_ID,S_A_L_NUMBER,S_A_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'70','20140915');
	UPDATE STOCK SET S_NUMBER_SUM=S_NUMBER_SUM+70,S_NUMBER_CUR=S_NUMBER_CUR+70
	WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆');
	INSERT INTO STOCK_ADD_LOG (S_ID,S_A_L_NUMBER,S_A_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'90','20140917');
	UPDATE STOCK SET S_NUMBER_SUM=S_NUMBER_SUM+90,S_NUMBER_CUR=S_NUMBER_CUR+90
	WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆');
	
	INSERT INTO STOCK_ADD_LOG (S_ID,S_A_L_NUMBER,S_A_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜')),'50','20140912');
	UPDATE STOCK SET S_NUMBER_SUM=S_NUMBER_SUM+50,S_NUMBER_CUR=S_NUMBER_CUR+50
	WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜');
	
	INSERT INTO STOCK_ADD_LOG (S_ID,S_A_L_NUMBER,S_A_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜')),'70','20140916');
	UPDATE STOCK SET S_NUMBER_SUM=S_NUMBER_SUM+70,S_NUMBER_CUR=S_NUMBER_CUR+70
	WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜');
	
	INSERT INTO STOCK_ADD_LOG (S_ID,S_A_L_NUMBER,S_A_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '青椒')),'100','20140917');
	UPDATE STOCK SET S_NUMBER_SUM=S_NUMBER_SUM+100,S_NUMBER_CUR=S_NUMBER_CUR+100
	WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '青椒');
	
	INSERT INTO STOCK_ADD_LOG (S_ID,S_A_L_NUMBER,S_A_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'70','20140917');
	UPDATE STOCK SET S_NUMBER_SUM=S_NUMBER_SUM+70,S_NUMBER_CUR=S_NUMBER_CUR+70
	WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '胡萝卜');
	
	INSERT INTO STOCK_ADD_LOG (S_ID,S_A_L_NUMBER,S_A_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'40','20140917');
	UPDATE STOCK SET S_NUMBER_SUM=S_NUMBER_SUM+40,S_NUMBER_CUR=S_NUMBER_CUR+40
	WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '大葱');
	
	INSERT INTO STOCK_ADD_LOG (S_ID,S_A_L_NUMBER,S_A_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'20','20140917');
	UPDATE STOCK SET S_NUMBER_SUM=S_NUMBER_SUM+20,S_NUMBER_CUR=S_NUMBER_CUR+20
	WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '姜');
	
	
	
	
	
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'12','20140914');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-12 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆');
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'23','20140915');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-23 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆');
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'19','20140916');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-19 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆');
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆')),'31','20140917');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-31 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '土豆');
	
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜')),'5','20140913');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-5 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜');
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜')),'9','20140914');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-9 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜');
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜')),'8','20140915');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-8 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜');
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜')),'14','20140916');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-14 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜');
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜')),'11','20140917');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-11 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '白菜');

	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '青椒')),'38','20140917');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-38 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '青椒');
	
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '胡萝卜')),'17','20140917');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-17 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '胡萝卜');
	
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '大葱')),'13','20140917');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-13 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '大葱');
	
	INSERT INTO STOCK_LOG (S_ID,S_L_NUMBER,S_L_TIME) 
	VALUES((SELECT S_ID FROM STOCK WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '姜')),'6','20140917');
	UPDATE STOCK SET S_NUMBER_CUR = S_NUMBER_CUR-6 WHERE S_N_ID = (SELECT S_N_ID FROM STOCK_NAME WHERE S_N_NAME = '姜');
	
	
	





--SELECT SQL
SELECT (TBA.SUM/TBA.CUR)*100 FROM (
SELECT sum(s_number_sum)sum,sum(s_number_cur) cur FROM STOCK
) TBA;